anwb:
  id: UA-60370009-11
  anonymize_ip: true
  autotrack: true
amnesty:
  id: UA-1282760-38
beeldengeluid:
  id: UA-24205219-12
blof:
  id: UA-6109912-30
concertatsea:
  id: UA-39955164-1
destijl:
  id: UA-101189236-1
ed:
  id: UA-74624429-2
grasnapolsky:
  id: UA-45712196-1
krisberry:
  id: UA-6109912-40
omroepbrabant:
  id: UA-116305-50
  anonymize_ip: true
  autotrack: true
psv:
  id: UA-2810339-12
ricostickstyphoon:
  id: UA-6109912-26
stephaniestruijk:
  id: UA-6109912-25
